global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "interview-coach"
    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets:
          - "interview-coach:8080"
       

